AWSTemplateFormatVersion: "2010-09-09"
Description: sam-ts-layers-example
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    #Layers:
    #  - !Ref RuntimeDependenciesLayer
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 10


Resources:

  Function1:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/f1/lambda.handler

  Function2:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/f2/lambda.handler
